In [2]:
from PIL import Image
import os, sys
import cv2
import numpy as np
from numpy import asarray
import csv

In [3]:
#Useful function
def createFileList(myDir, format='.png'):
    fileList = []
    print(myDir)
    
    for root, dirs, files in os.walk(myDir, topdown=False):
        for name in files:
            if name.endswith(format):
                fullName = os.path.join(root, name)
                fileList.append(fullName)
    return fileList

In [4]:
# load the original image
myFileList = createFileList('C:/Users/ACER/FINAL/database/nomask/')

for file in myFileList:
    print(file)
    img_file = Image.open(file)
    # img_file.show()

    # get original image parameters...
    width, height = img_file.size
    format = img_file.format
    mode = img_file.mode

    # Make image Greyscale
    img_grey = img_file.convert('L')
    #img_grey.save('result.png')
    #img_grey.show()

    # Save Greyscale values
    value = np.asarray(img_grey.getdata(), dtype=np.int).reshape((img_grey.size[1], img_grey.size[0]))
    value = value.flatten()
    print(value)
    with open("nomask.csv", 'a') as f:
        writer = csv.writer(f)
        writer.writerow(value)

C:/Users/ACER/FINAL/database/nomask/
C:/Users/ACER/FINAL/database/nomask/0.png
[233 232 230 ... 147 148 148]
C:/Users/ACER/FINAL/database/nomask/1.png
[221 222 224 ... 127 127 126]
C:/Users/ACER/FINAL/database/nomask/10.png
[218 219 219 ... 122 124 124]
C:/Users/ACER/FINAL/database/nomask/100.png
[198 197 198 ...  80  83  90]
C:/Users/ACER/FINAL/database/nomask/101.png
[198 197 198 ...  80  83  90]
C:/Users/ACER/FINAL/database/nomask/102.png
[213 213 212 ...  99 100 104]
C:/Users/ACER/FINAL/database/nomask/103.png
[201 201 202 ...  33  29  24]
C:/Users/ACER/FINAL/database/nomask/104.png
[ 27  26  28 ... 122 122 123]
C:/Users/ACER/FINAL/database/nomask/105.png
[ 25  25  32 ... 131 131 132]
C:/Users/ACER/FINAL/database/nomask/106.png
[156 140 127 ... 146 146 146]
C:/Users/ACER/FINAL/database/nomask/107.png
[154 149 135 ... 151 151 152]
C:/Users/ACER/FINAL/database/nomask/108.png
[ 66  58  56 ... 141 143 143]
C:/Users/ACER/FINAL/database/nomask/109.png
[158 112  76 ... 126 130 130]
C:/Use

[213 212 213 ... 147 148 148]
C:/Users/ACER/FINAL/database/nomask/21.png
[213 214 214 ... 143 142 145]
C:/Users/ACER/FINAL/database/nomask/22.png
[216 216 216 ...  50  44  44]
C:/Users/ACER/FINAL/database/nomask/23.png
[220 212 166 ... 129 129 130]
C:/Users/ACER/FINAL/database/nomask/24.png
[212 210 208 ...  41  42  47]
C:/Users/ACER/FINAL/database/nomask/25.png
[213 213 211 ...  43  43  47]
C:/Users/ACER/FINAL/database/nomask/26.png
[212 212 212 ...  43  46  49]
C:/Users/ACER/FINAL/database/nomask/27.png
[215 214 215 ...  41  41  43]
C:/Users/ACER/FINAL/database/nomask/28.png
[216 215 214 ...  28  31  29]
C:/Users/ACER/FINAL/database/nomask/29.png
[220 219 221 ...  34  34  38]
C:/Users/ACER/FINAL/database/nomask/3.png
[204 204 204 ...  61  63  89]
C:/Users/ACER/FINAL/database/nomask/30.png
[203 197 197 ... 146 147 147]
C:/Users/ACER/FINAL/database/nomask/31.png
[194 192 190 ... 144 145 146]
C:/Users/ACER/FINAL/database/nomask/32.png
[209 207 207 ... 112 110 112]
C:/Users/ACER/FINAL/da

In [5]:
#import pandas as pd

In [6]:
directory = 'C:\\Users\\ACER\FINAL\\model_dataset\\'
filename = input('Enter your name: ')

Enter your name: nomask


In [7]:
# First read into csv with pandas
data_img = np.genfromtxt("C:/Users/ACER/FINAL/nomask.csv", delimiter=",")
 # Save numpy as npy
np.save(directory+filename+'.npy', data_img)